Added instructions for locally downloading YAML
rh-aiservices-bu/insurance-claim-processing pull request #167
Opened 2024-03-29 18:28 UTC by cedricclyburn

Via #166

2024-04-02 12:48 UTC, erwangranger commented
Thanks for the PR and clarifications it brings. 

That makes sense. We might have to change the PR to merge in "Dev" branch first, and then "main".  
We'll include this into our next set of changes to the materials.

2024-04-02 12:49 UTC, cedricclyburn commented
Gotcha, thank you @erwangranger, just let me know and I can move the base. Cheers!

2024-04-02 19:27 UTC, guimou requested changes
Thanks a lot!
As @erwangranger said, the only needed changes are the dev branch instead of main.
I can take care of it if not practical for you.

2024-04-02 19:27 UTC, guimou commented on bootstrap/applicationset/applicationset-bootstrap.yaml
Can you change the targetRevision back to dev? We merge into dev first to fully test the deployment, then only to main.

2024-04-02 19:27 UTC, guimou commented on content/antora.yml
use dev branch

2024-04-02 19:27 UTC, guimou commented on content/modules/ROOT/pages/05-03-web-app-deploy-application.adoc
dev branch

2024-04-08 15:32 UTC, cedricclyburn commented
Thanks for the heads up @guimou! Good luck at Summit, hope to meet you there :)

2024-04-09 20:14 UTC, merged